
#include "cvm.h"

#include "icvmerr.h"

// Copyright (C) 2000,2001 Bob Dayley

#ifdef __WIN32__
#include <windows.h>
#endif

#ifndef __WIN32__
#include <errno.h>
#include  "icvmsys.h"

#endif

int i_errno;


// this call will be obsolete
void icvm_SetErr(void){
	R_ERRNO1=TranslateErrToICVM(errno);
};




#ifndef __WIN32__


int TranslateErrToICVM(int err){

	int result;

	switch(err){


		case 0:
			result=0;break;
		case EBADF:
			result=ICVM_EBADF;break;
		case EPERM:
			result=ICVM_EPERM;break;
		case ENOENT:
			result=ICVM_ENOENT;break;
		case ESRCH:
			result=ICVM_ESRCH;break;
		case EINTR:
			result=ICVM_EINTR;break;
		case ENXIO:
			result=ICVM_ENXIO;break;
		case E2BIG:
			result=ICVM_E2BIG;break;
		case ENOEXEC:
			result=ICVM_ENOEXEC;break;
		case ECHILD:
			result=ICVM_ECHILD;break;
		case EDEADLK:
			result=ICVM_EDEADLK;break;
		case ENOMEM:
			result=ICVM_ENOMEM;break;
		case EACCES:
			result=ICVM_EACCES;break;
		case EFAULT:
			result=ICVM_EFAULT;break;
		case ENOTBLK:
			result=ICVM_ENOTBLK;break;
		case EBUSY:
			result=ICVM_EBUSY;break;
		case EEXIST:
			result=ICVM_EEXIST;break;
		case EXDEV:
			result=ICVM_EXDEV;break;
		case ENODEV:
			result=ICVM_ENODEV;break;
		case ENOTDIR:
			result=ICVM_ENOTDIR;break;
		case EISDIR:
			result=ICVM_EISDIR;break;
		case EINVAL:
			result=ICVM_EINVAL;break;
		case ENFILE:
			result=ICVM_ENFILE;break;
		case EMFILE:
			result=ICVM_EMFILE;break;
		case ENOTTY:
			result=ICVM_ENOTTY;break;
		case ETXTBSY:
			result=ICVM_ETXTBSY;break;
		case EFBIG:
			result=ICVM_EFBIG;break;
		case ENOSPC:
			result=ICVM_ENOSPC;break;
		case ESPIPE:
			result=ICVM_ESPIPE;break;
		case EROFS:
			result=ICVM_EROFS;break;
		case EMLINK:
			result=ICVM_EMLINK;break;
		case EPIPE:
			result=ICVM_EPIPE;break;
		case EDOM:
			result=ICVM_EDOM;break;
		case ERANGE:
			result=ICVM_ERANGE;break;
		case EAGAIN:
			result=ICVM_EAGAIN;break;
		case EINPROGRESS:
			result=ICVM_EINPROGRESS;break;
		case EALREADY:
			result=ICVM_EALREADY;break;
		case ENOTSOCK:
			result=ICVM_ENOTSOCK;break;
		case EDESTADDRREQ:
			result=ICVM_EDESTADDRREQ;break;
		case EMSGSIZE:
			result=ICVM_EMSGSIZE;break;
		case EPROTOTYPE:
			result=ICVM_EPROTOTYPE;break;
		case ENOPROTOOPT:
			result=ICVM_ENOPROTOOPT;break;
		case EPROTONOSUPPORT:
			result=ICVM_EPROTONOSUPPORT;break;
		case ESOCKTNOSUPPORT:
			result=ICVM_ESOCKTNOSUPPORT;break;
		case EOPNOTSUPP:
			result=ICVM_EOPNOTSUPP;break;
		case EPFNOSUPPORT:
			result=ICVM_EPFNOSUPPORT;break;
		case EAFNOSUPPORT:
			result=ICVM_EAFNOSUPPORT;break;
		case EADDRINUSE:
			result=ICVM_EADDRINUSE;break;
		case EADDRNOTAVAIL:
			result=ICVM_EADDRNOTAVAIL;break;
		case ENETDOWN:
			result=ICVM_ENETDOWN;break;
		case ENETUNREACH:
			result=ICVM_ENETUNREACH;break;
		case ENETRESET:
			result=ICVM_ENETRESET;break;
		case ECONNABORTED:
			result=ICVM_ECONNABORTED;break;
		case ECONNRESET:
			result=ICVM_ECONNRESET;break;
		case ENOBUFS:
			result=ICVM_ENOBUFS;break;
		case EISCONN:
			result=ICVM_EISCONN;break;
		case ENOTCONN:
			result=ICVM_ENOTCONN;break;
		case ESHUTDOWN:
			result=ICVM_ESHUTDOWN;break;
		case ETOOMANYREFS:
			result=ICVM_ETOOMANYREFS;break;
		case ETIMEDOUT:
			result=ICVM_ETIMEDOUT;break;
		case ECONNREFUSED:
			result=ICVM_ECONNREFUSED;break;
		case ELOOP:
			result=ICVM_ELOOP;break;
		case ENAMETOOLONG:
			result=ICVM_ENAMETOOLONG;break;
		case EHOSTDOWN:
			result=ICVM_EHOSTDOWN;break;
		case EHOSTUNREACH:
			result=ICVM_EHOSTUNREACH;break;
		case ENOTEMPTY:
			result=ICVM_ENOTEMPTY;break;
#ifdef EPROCLIM
		case EPROCLIM:
			result=ICVM_EPROCLIM;break;
#endif
		case EUSERS:
			result=ICVM_EUSERS;break;
		case EDQUOT:
			result=ICVM_EDQUOT;break;
		case ESTALE:
			result=ICVM_ESTALE;break;
		case EREMOTE:
			result=ICVM_EREMOTE;break;
#ifdef EBADRPC
		case EBADRPC:
			result=ICVM_EBADRPC;break;
#endif
#ifdef ERPCMISMATCH
		case ERPCMISMATCH:
			result=ICVM_ERPCMISMATCH;break;
#endif
#ifdef EPROGUNAVAIL
		case EPROGUNAVAIL:
			result=ICVM_EPROGUNAVAIL;break;
#endif
#ifdef EPROGMISMATCH
		case EPROGMISMATCH:
			result=ICVM_EPROGMISMATCH;break;
#endif
#ifdef EPROCUNAVAIL
		case EPROCUNAVAIL:
			result=ICVM_EPROCUNAVAIL;break;
#endif
		case ENOLCK:
			result=ICVM_ENOLCK;break;
		case ENOSYS:
			result=ICVM_ENOSYS;break;
#ifdef EFTYPE
		case EFTYPE:
			result=ICVM_EFTYPE;break;
#endif


		default:

			result=ICVM_EUNKNOWN;break;
	}
	return result;
}

#endif // !__WIN32__


#ifdef __WIN32__

// ########### NOTE -- THIS IS FAR FROM COMPLETE OR ACCURATE  ###################

int TranslateErrToICVM(int err){

	int result;

	switch(err){

#ifdef NOT_NOW // ********************************

		case 0:
			result=0;break;
		case EINTR:
			result=ICVM_EINTR;break;
		case ENXIO:
			result=ICVM_ENXIO;break;
		case E2BIG:
			result=ICVM_E2BIG;break;
		case ENOEXEC:
			result=ICVM_ENOEXEC;break;
		case ENOTBLK:
			result=ICVM_ENOTBLK;break;
		case EXDEV:
			result=ICVM_EXDEV;break;
		case ENOTDIR:
			result=ICVM_ENOTDIR;break;
		case EISDIR:
			result=ICVM_EISDIR;break;
		case ENFILE:
			result=ICVM_ENFILE;break;
		case ENOTTY:
			result=ICVM_ENOTTY;break;
		case ETXTBSY:
			result=ICVM_ETXTBSY;break;
		case EROFS:
			result=ICVM_EROFS;break;
		case EMLINK:
			result=ICVM_EMLINK;break;
		case EDOM:
			result=ICVM_EDOM;break;
		case ERANGE:
			result=ICVM_ERANGE;break;
		case EAGAIN:
			result=ICVM_EAGAIN;break;
		case EINPROGRESS:
			result=ICVM_EINPROGRESS;break;
		case EALREADY:
			result=ICVM_EALREADY;break;
		case ENOTSOCK:
			result=ICVM_ENOTSOCK;break;
		case EDESTADDRREQ:
			result=ICVM_EDESTADDRREQ;break;
		case EMSGSIZE:
			result=ICVM_EMSGSIZE;break;
		case EPROTOTYPE:
			result=ICVM_EPROTOTYPE;break;
		case ENOPROTOOPT:
			result=ICVM_ENOPROTOOPT;break;
		case EPROTONOSUPPORT:
			result=ICVM_EPROTONOSUPPORT;break;
		case ESOCKTNOSUPPORT:
			result=ICVM_ESOCKTNOSUPPORT;break;
		case EOPNOTSUPP:
			result=ICVM_EOPNOTSUPP;break;
		case EPFNOSUPPORT:
			result=ICVM_EPFNOSUPPORT;break;
		case EAFNOSUPPORT:
			result=ICVM_EAFNOSUPPORT;break;
		case EADDRINUSE:
			result=ICVM_EADDRINUSE;break;
		case EADDRNOTAVAIL:
			result=ICVM_EADDRNOTAVAIL;break;
		case ENETDOWN:
			result=ICVM_ENETDOWN;break;
		case ENETUNREACH:
			result=ICVM_ENETUNREACH;break;
		case ENETRESET:
			result=ICVM_ENETRESET;break;
		case ECONNABORTED:
			result=ICVM_ECONNABORTED;break;
		case ECONNRESET:
			result=ICVM_ECONNRESET;break;
		case ENOBUFS:
			result=ICVM_ENOBUFS;break;
		case EISCONN:
			result=ICVM_EISCONN;break;
		case ENOTCONN:
			result=ICVM_ENOTCONN;break;
		case ESHUTDOWN:
			result=ICVM_ESHUTDOWN;break;
		case ETOOMANYREFS:
			result=ICVM_ETOOMANYREFS;break;
		case ECONNREFUSED:
			result=ICVM_ECONNREFUSED;break;
		case ELOOP:
			result=ICVM_ELOOP;break;
		case ENAMETOOLONG:
			result=ICVM_ENAMETOOLONG;break;
		case EHOSTDOWN:
			result=ICVM_EHOSTDOWN;break;
		case EHOSTUNREACH:
			result=ICVM_EHOSTUNREACH;break;
		case ENOTEMPTY:
			result=ICVM_ENOTEMPTY;break;
#ifdef EPROCLIM
		case EPROCLIM:
			result=ICVM_EPROCLIM;break;
#endif
		case EUSERS:
			result=ICVM_EUSERS;break;
		case EDQUOT:
			result=ICVM_EDQUOT;break;
		case ESTALE:
			result=ICVM_ESTALE;break;
		case EREMOTE:
			result=ICVM_EREMOTE;break;
#ifdef EBADRPC
		case EBADRPC:
			result=ICVM_EBADRPC;break;
#endif
#ifdef ERPCMISMATCH
		case ERPCMISMATCH:
			result=ICVM_ERPCMISMATCH;break;
#endif
#ifdef EPROGUNAVAIL
		case EPROGUNAVAIL:
			result=ICVM_EPROGUNAVAIL;break;
#endif
#ifdef EPROGMISMATCH
		case EPROGMISMATCH:
			result=ICVM_EPROGMISMATCH;break;
#endif
#ifdef EPROCUNAVAIL
		case EPROCUNAVAIL:
			result=ICVM_EPROCUNAVAIL;break;
#endif
		case ENOLCK:
			result=ICVM_ENOLCK;break;
#ifdef EFTYPE
		case EFTYPE:
			result=ICVM_EFTYPE;break;
#endif

#endif NOT_NOW // ********************************

		case 0:
			result=0;break;

		case ERROR_WAIT_NO_CHILDREN:
			result=ICVM_ECHILD;break;

		case ERROR_PROC_NOT_FOUND:
			result=ICVM_ESRCH;break;

		case ERROR_INVALID_PARAMETER:
			result=ICVM_EINVAL;break;


		case ERROR_DISK_FULL:
		case ERROR_HANDLE_DISK_FULL:
		case ERROR_PRINTQ_FULL:
		case ERROR_NO_SPOOL_SPACE:
			result=ICVM_ENOSPC;break;

		case ERROR_INVALID_HANDLE:
		case ERROR_INVALID_TARGET_HANDLE:
			result=ICVM_EBADF;break;

		case ERROR_NOT_DOS_DISK:
		case ERROR_SECTOR_NOT_FOUND:
		case ERROR_OUT_OF_PAPER:
		case ERROR_GEN_FAILURE:
		case ERROR_READ_FAULT:
		case ERROR_FAIL_I24:
		case ERROR_CRC:
		case ERROR_INVALID_BLOCK:
		case ERROR_INVALID_DATA:
		case ERROR_IO_DEVICE:
		case ERROR_ADAP_HDW_ERR:
		case ERROR_NET_WRITE_FAULT:
		case ERROR_FLOPPY_ID_MARK_NOT_FOUND:
		case ERROR_FLOPPY_WRONG_CYLINDER:
		case ERROR_FLOPPY_UNKNOWN_ERROR:
		case ERROR_FLOPPY_BAD_REGISTERS:
		case ERROR_DISK_RECALIBRATE_FAILED:
		case ERROR_DISK_OPERATION_FAILED:
		case ERROR_DISK_RESET_FAILED:
			result=ICVM_EIO;break;


		case ERROR_FILE_NOT_FOUND:
		case ERROR_PATH_NOT_FOUND:
		case ERROR_INVALID_DRIVE:
		case ERROR_BAD_UNIT:
			result=ICVM_ENOENT;break;


		case ERROR_ACCESS_DENIED:
		case ERROR_INVALID_ACCESS:
		case ERROR_NETWORK_ACCESS_DENIED:
		case ERROR_NOACCESS:
		case ERROR_EA_ACCESS_DENIED:
		case ERROR_DIRECT_ACCESS_HANDLE:
			result=ICVM_EACCES;break;

		case ERROR_WRITE_PROTECT:
			result=ICVM_EPERM;break;

		case ERROR_OUTOFMEMORY:
		case ERROR_NOT_ENOUGH_MEMORY:
		case ERROR_NOT_ENOUGH_SERVER_MEMORY:
		case ERROR_OUT_OF_STRUCTURES:
			result=ICVM_ENOMEM;break;


		case ERROR_TOO_MANY_OPEN_FILES:
			result=ICVM_EMFILE;break;

		case ERROR_FILE_EXISTS:
			result=ICVM_EEXIST;break;

		case TYPE_E_SIZETOOBIG:
			result=ICVM_EFBIG;break;

		case ERROR_BROKEN_PIPE:
		case ERROR_BAD_PIPE:
		case ERROR_PIPE_NOT_CONNECTED:
			result=ICVM_EPIPE;break;

		case ERROR_NEGATIVE_SEEK:
		case ERROR_SEEK_ON_DEVICE:
		case ERROR_SEEK:
			result=ICVM_ESPIPE;break;

		case ERROR_INVALID_FUNCTION:
		case ERROR_CALL_NOT_IMPLEMENTED:
			result=ICVM_ENOSYS;break;

		case ERROR_SHARING_VIOLATION:
		case ERROR_LOCK_VIOLATION:
		case ERROR_BUSY_DRIVE:
		case ERROR_PATH_BUSY:
		case ERROR_PIPE_BUSY:
		case ERROR_IRQ_BUSY:
		case ERROR_DRIVE_LOCKED:
		case ERROR_BUSY:
		case ERROR_LOCKED:
		case ERROR_SERVICE_DATABASE_LOCKED:
		case ERROR_SCREEN_ALREADY_LOCKED:
		case STG_E_LOCKVIOLATION:
		case STG_E_INUSE:
			result=ICVM_EBUSY;break;

		case ERROR_SEM_TIMEOUT:
		case ERROR_SERVICE_REQUEST_TIMEOUT:
		case ERROR_COUNTER_TIMEOUT:
			result=ICVM_ETIMEDOUT;break;

		case ERROR_POSSIBLE_DEADLOCK:
			result=ICVM_EDEADLK;break;

		case ERROR_NOT_SUPPORTED:
			result=ICVM_ENODEV;break;

		case ERROR_INVALID_ADDRESS:
			result=ICVM_EFAULT;break;

#ifdef NOT_NOW // THESE NEED TO BE CATORGORIZED

		case ERROR_DIRECTORY:
		case ERROR_NO_DATA:
		case ERROR_HANDLE_EOF:
		case ERROR_ARENA_TRASHED:
		case ERROR_BAD_ENVIRONMENT:
		case ERROR_BAD_FORMAT:
		case ERROR_CURRENT_DIRECTORY:
		case ERROR_NOT_SAME_DEVICE:
		case ERROR_NO_MORE_FILES:
		case ERROR_NOT_READY:
		case ERROR_BAD_COMMAND:
		case ERROR_BAD_LENGTH:
		case ERROR_WRONG_DISK:
		case ERROR_SHARING_BUFFER_EXCEEDED:
		case ERROR_REM_NOT_LIST:
		case ERROR_DUP_NAME:
		case ERROR_BAD_NETPATH:
		case ERROR_NETWORK_BUSY:
		case ERROR_DEV_NOT_EXIST:
		case ERROR_TOO_MANY_CMDS:
		case ERROR_BAD_NET_RESP:
		case ERROR_UNEXP_NET_ERR:
		case ERROR_BAD_REM_ADAP:
		case ERROR_PRINT_CANCELLED:
		case ERROR_NETNAME_DELETED:
		case ERROR_BAD_DEV_TYPE:
		case ERROR_BAD_NET_NAME:
		case ERROR_TOO_MANY_NAMES:
		case ERROR_TOO_MANY_SESS:
		case ERROR_SHARING_PAUSED:
		case ERROR_REQ_NOT_ACCEP:
		case ERROR_REDIR_PAUSED:
		case ERROR_CANNOT_MAKE:
		case ERROR_ALREADY_ASSIGNED:
		case ERROR_INVALID_PASSWORD:
		case ERROR_NO_PROC_SLOTS:
		case ERROR_TOO_MANY_SEMAPHORES:
		case ERROR_EXCL_SEM_ALREADY_OWNED:
		case ERROR_SEM_IS_SET:
		case ERROR_TOO_MANY_SEM_REQUESTS:
		case ERROR_INVALID_AT_INTERRUPT_TIME:
		case ERROR_SEM_OWNER_DIED:
		case ERROR_SEM_USER_LIMIT:
		case ERROR_DISK_CHANGE:
		case ERROR_OPEN_FAILED:
		case ERROR_BUFFER_OVERFLOW:
		case ERROR_NO_MORE_SEARCH_HANDLES:
		case ERROR_INVALID_CATEGORY:
		case ERROR_INVALID_VERIFY_SWITCH:
		case ERROR_BAD_DRIVER_LEVEL:
		case ERROR_INSUFFICIENT_BUFFER:
		case ERROR_INVALID_NAME:
		case ERROR_INVALID_LEVEL:
		case ERROR_NO_VOLUME_LABEL:
		case ERROR_MOD_NOT_FOUND:
		case ERROR_CHILD_NOT_COMPLETE:

		case ERROR_SYSTEM_TRACE:
		case ERROR_INVALID_EVENT_COUNT:
		case ERROR_TOO_MANY_MUXWAITERS:
		case ERROR_INVALID_LIST_FORMAT:
		case ERROR_LABEL_TOO_LONG:
		case ERROR_TOO_MANY_TCBS:
		case ERROR_SIGNAL_REFUSED:
		case ERROR_DISCARDED:
		case ERROR_NOT_LOCKED:
		case ERROR_BAD_THREADID_ADDR:
		case ERROR_BAD_ARGUMENTS:
		case ERROR_BAD_PATHNAME:
		case ERROR_SIGNAL_PENDING:
		case ERROR_MAX_THRDS_REACHED:
		case ERROR_LOCK_FAILED:
		case ERROR_CANCEL_VIOLATION:
		case ERROR_ATOMIC_LOCKS_NOT_SUPPORTED:
		case ERROR_INVALID_SEGMENT_NUMBER:
		case ERROR_INVALID_ORDINAL:
		case ERROR_ALREADY_EXISTS:
		case ERROR_INVALID_FLAG_NUMBER:
		case ERROR_SEM_NOT_FOUND:
		case ERROR_INVALID_STARTING_CODESEG:
		case ERROR_INVALID_STACKSEG:
		case ERROR_INVALID_MODULETYPE:
		case ERROR_INVALID_EXE_SIGNATURE:
		case ERROR_EXE_MARKED_INVALID:
		case ERROR_BAD_EXE_FORMAT:
		case ERROR_ITERATED_DATA_EXCEEDS_64k:
		case ERROR_INVALID_MINALLOCSIZE:
		case ERROR_DYNLINK_FROM_INVALID_RING:
		case ERROR_IOPL_NOT_ENABLED:
		case ERROR_INVALID_SEGDPL:
		case ERROR_AUTODATASEG_EXCEEDS_64k:
		case ERROR_RING2SEG_MUST_BE_MOVABLE:
		case ERROR_RELOC_CHAIN_XEEDS_SEGLIM:
		case ERROR_INFLOOP_IN_RELOC_CHAIN:
		case ERROR_ENVVAR_NOT_FOUND:
		case ERROR_NO_SIGNAL_SENT:
		case ERROR_FILENAME_EXCED_RANGE:
		case ERROR_RING2_STACK_IN_USE:
		case ERROR_META_EXPANSION_TOO_LONG:
		case ERROR_INVALID_SIGNAL_NUMBER:
		case ERROR_THREAD_1_INACTIVE:
		case ERROR_TOO_MANY_MODULES:
		case ERROR_NESTING_NOT_ALLOWED:
		case ERROR_MORE_DATA:
		case ERROR_VC_DISCONNECTED:
		case ERROR_INVALID_EA_NAME:
		case ERROR_EA_LIST_INCONSISTENT:
		case ERROR_NO_MORE_ITEMS:
		case ERROR_CANNOT_COPY:
		case ERROR_EAS_DIDNT_FIT:
		case ERROR_EA_FILE_CORRUPT:
		case ERROR_EA_TABLE_FULL:
		case ERROR_INVALID_EA_HANDLE:
		case ERROR_EAS_NOT_SUPPORTED:
		case ERROR_NOT_OWNER:
		case ERROR_TOO_MANY_POSTS:
		case ERROR_PARTIAL_COPY:
		case ERROR_MR_MID_NOT_FOUND:
		case ERROR_ARITHMETIC_OVERFLOW:
		case ERROR_PIPE_CONNECTED:
		case ERROR_PIPE_LISTENING:
		case ERROR_OPERATION_ABORTED:
		case ERROR_IO_INCOMPLETE:
		case ERROR_IO_PENDING:
		case ERROR_SWAPERROR:
		case ERROR_STACK_OVERFLOW:
		case ERROR_INVALID_MESSAGE:
		case ERROR_CAN_NOT_COMPLETE:
		case ERROR_INVALID_FLAGS:
		case ERROR_UNRECOGNIZED_VOLUME:
		case ERROR_FILE_INVALID:
		case ERROR_FULLSCREEN_MODE:



		case ERROR_NO_TOKEN:
		case ERROR_BADDB:
		case ERROR_BADKEY:
		case ERROR_CANTOPEN:
		case ERROR_CANTREAD:
		case ERROR_CANTWRITE:
		case ERROR_REGISTRY_RECOVERED:
		case ERROR_REGISTRY_CORRUPT:
		case ERROR_REGISTRY_IO_FAILED:
		case ERROR_NOT_REGISTRY_FILE:
		case ERROR_KEY_DELETED:
		case ERROR_NO_LOG_SPACE:
		case ERROR_KEY_HAS_CHILDREN:
		case ERROR_CHILD_MUST_BE_VOLATILE:
		case ERROR_NOTIFY_ENUM_DIR:


		case ERROR_DEPENDENT_SERVICES_RUNNING:
		case ERROR_INVALID_SERVICE_CONTROL:
		case ERROR_SERVICE_NO_THREAD:
		case ERROR_SERVICE_ALREADY_RUNNING:
		case ERROR_INVALID_SERVICE_ACCOUNT:
		case ERROR_SERVICE_DISABLED:
		case ERROR_CIRCULAR_DEPENDENCY:
		case ERROR_SERVICE_DOES_NOT_EXIST:
		case ERROR_SERVICE_CANNOT_ACCEPT_CTRL:
		case ERROR_SERVICE_NOT_ACTIVE:
		case ERROR_FAILED_SERVICE_CONTROLLER_CONNECT:
		case ERROR_EXCEPTION_IN_SERVICE:
		case ERROR_DATABASE_DOES_NOT_EXIST:
		case ERROR_SERVICE_SPECIFIC_ERROR:
		case ERROR_PROCESS_ABORTED:
		case ERROR_SERVICE_DEPENDENCY_FAIL:
		case ERROR_SERVICE_LOGON_FAILED:
		case ERROR_SERVICE_START_HANG:
		case ERROR_INVALID_SERVICE_LOCK:
		case ERROR_SERVICE_MARKED_FOR_DELETE:
		case ERROR_SERVICE_EXISTS:
		case ERROR_ALREADY_RUNNING_LKG:
		case ERROR_SERVICE_DEPENDENCY_DELETED:
		case ERROR_BOOT_ALREADY_ACCEPTED:
		case ERROR_SERVICE_NEVER_STARTED:
		case ERROR_DUPLICATE_SERVICE_NAME:
		case ERROR_END_OF_MEDIA:
		case ERROR_FILEMARK_DETECTED:
		case ERROR_BEGINNING_OF_MEDIA:
		case ERROR_SETMARK_DETECTED:
		case ERROR_NO_DATA_DETECTED:
		case ERROR_PARTITION_FAILURE:
		case ERROR_INVALID_BLOCK_LENGTH:
		case ERROR_DEVICE_NOT_PARTITIONED:
		case ERROR_UNABLE_TO_LOCK_MEDIA:
		case ERROR_UNABLE_TO_UNLOAD_MEDIA:
		case ERROR_MEDIA_CHANGED:
		case ERROR_BUS_RESET:
		case ERROR_NO_MEDIA_IN_DRIVE:
		case ERROR_NO_UNICODE_TRANSLATION:
		case ERROR_DLL_INIT_FAILED:
		case ERROR_SHUTDOWN_IN_PROGRESS:
		case ERROR_NO_SHUTDOWN_IN_PROGRESS:
		case ERROR_SERIAL_NO_DEVICE:
		case ERROR_MORE_WRITES:
		case ERROR_EOM_OVERFLOW:
		case ERROR_MAPPED_ALIGNMENT:
		case ERROR_SET_POWER_STATE_VETOED:
		case ERROR_SET_POWER_STATE_FAILED:
		case ERROR_OLD_WIN_VERSION:
		case ERROR_APP_WRONG_OS:
		case ERROR_SINGLE_INSTANCE_APP:
		case ERROR_RMODE_APP:
		case ERROR_INVALID_DLL:
		case ERROR_NO_ASSOCIATION:
		case ERROR_DDE_FAIL:
		case ERROR_DLL_NOT_FOUND:
		case ERROR_BAD_USERNAME:
		case ERROR_NOT_CONNECTED:
		case ERROR_OPEN_FILES:
		case ERROR_ACTIVE_CONNECTIONS:
		case ERROR_DEVICE_IN_USE:
		case ERROR_BAD_DEVICE:
		case ERROR_CONNECTION_UNAVAIL:
		case ERROR_DEVICE_ALREADY_REMEMBERED:
		case ERROR_NO_NET_OR_BAD_PATH:
		case ERROR_BAD_PROVIDER:
		case ERROR_CANNOT_OPEN_PROFILE:
		case ERROR_BAD_PROFILE:
		case ERROR_NOT_CONTAINER:
		case ERROR_EXTENDED_ERROR:
		case ERROR_INVALID_GROUPNAME:
		case ERROR_INVALID_COMPUTERNAME:
		case ERROR_INVALID_EVENTNAME:
		case ERROR_INVALID_DOMAINNAME:
		case ERROR_INVALID_SERVICENAME:
		case ERROR_INVALID_NETNAME:
		case ERROR_INVALID_SHARENAME:
		case ERROR_INVALID_PASSWORDNAME:
		case ERROR_INVALID_MESSAGENAME:
		case ERROR_INVALID_MESSAGEDEST:
		case ERROR_SESSION_CREDENTIAL_CONFLICT:
		case ERROR_REMOTE_SESSION_LIMIT_EXCEEDED:
		case ERROR_DUP_DOMAINNAME:
		case ERROR_NO_NETWORK:
		case ERROR_CANCELLED:
		case ERROR_USER_MAPPED_FILE:
		case ERROR_CONNECTION_REFUSED:
		case ERROR_GRACEFUL_DISCONNECT:
		case ERROR_ADDRESS_ALREADY_ASSOCIATED:
		case ERROR_ADDRESS_NOT_ASSOCIATED:
		case ERROR_CONNECTION_INVALID:
		case ERROR_CONNECTION_ACTIVE:
		case ERROR_NETWORK_UNREACHABLE:
		case ERROR_HOST_UNREACHABLE:
		case ERROR_PROTOCOL_UNREACHABLE:
		case ERROR_PORT_UNREACHABLE:
		case ERROR_REQUEST_ABORTED:
		case ERROR_CONNECTION_ABORTED:
		case ERROR_RETRY:
		case ERROR_CONNECTION_COUNT_LIMIT:
		case ERROR_LOGIN_TIME_RESTRICTION:
		case ERROR_LOGIN_WKSTA_RESTRICTION:
		case ERROR_INCORRECT_ADDRESS:
		case ERROR_ALREADY_REGISTERED:
		case ERROR_SERVICE_NOT_FOUND:
		case ERROR_NOT_AUTHENTICATED:
		case ERROR_NOT_LOGGED_ON:
		case ERROR_CONTINUE:
		case ERROR_ALREADY_INITIALIZED:
		case ERROR_NO_MORE_DEVICES:
		case ERROR_NOT_ALL_ASSIGNED:
		case ERROR_SOME_NOT_MAPPED:
		case ERROR_NO_QUOTAS_FOR_ACCOUNT:
		case ERROR_LOCAL_USER_SESSION_KEY:
		case ERROR_NULL_LM_PASSWORD:
		case ERROR_UNKNOWN_REVISION:
		case ERROR_REVISION_MISMATCH:
		case ERROR_INVALID_OWNER:
		case ERROR_INVALID_PRIMARY_GROUP:
		case ERROR_NO_IMPERSONATION_TOKEN:
		case ERROR_CANT_DISABLE_MANDATORY:
		case ERROR_NO_LOGON_SERVERS:
		case ERROR_NO_SUCH_LOGON_SESSION:
		case ERROR_NO_SUCH_PRIVILEGE:
		case ERROR_PRIVILEGE_NOT_HELD:
		case ERROR_INVALID_ACCOUNT_NAME:
		case ERROR_USER_EXISTS:
		case ERROR_NO_SUCH_USER:
		case ERROR_GROUP_EXISTS:
		case ERROR_NO_SUCH_GROUP:
		case ERROR_MEMBER_IN_GROUP:
		case ERROR_MEMBER_NOT_IN_GROUP:
		case ERROR_LAST_ADMIN:
		case ERROR_WRONG_PASSWORD:
		case ERROR_ILL_FORMED_PASSWORD:
		case ERROR_PASSWORD_RESTRICTION:
		case ERROR_LOGON_FAILURE:
		case ERROR_ACCOUNT_RESTRICTION:
		case ERROR_INVALID_LOGON_HOURS:
		case ERROR_INVALID_WORKSTATION:
		case ERROR_PASSWORD_EXPIRED:
		case ERROR_ACCOUNT_DISABLED:
		case ERROR_NONE_MAPPED:
		case ERROR_TOO_MANY_LUIDS_REQUESTED:
		case ERROR_LUIDS_EXHAUSTED:
		case ERROR_INVALID_SUB_AUTHORITY:
		case ERROR_INVALID_ACL:
		case ERROR_INVALID_SID:
		case ERROR_INVALID_SECURITY_DESCR:
		case ERROR_BAD_INHERITANCE_ACL:
		case ERROR_SERVER_DISABLED:
		case ERROR_SERVER_NOT_DISABLED:
		case ERROR_INVALID_ID_AUTHORITY:
		case ERROR_ALLOTTED_SPACE_EXCEEDED:
		case ERROR_INVALID_GROUP_ATTRIBUTES:
		case ERROR_BAD_IMPERSONATION_LEVEL:
		case ERROR_CANT_OPEN_ANONYMOUS:
		case ERROR_BAD_VALIDATION_CLASS:
		case ERROR_BAD_TOKEN_TYPE:
		case ERROR_NO_SECURITY_ON_OBJECT:
		case ERROR_CANT_ACCESS_DOMAIN_INFO:
		case ERROR_INVALID_SERVER_STATE:
		case ERROR_INVALID_DOMAIN_STATE:
		case ERROR_INVALID_DOMAIN_ROLE:
		case ERROR_NO_SUCH_DOMAIN:
		case ERROR_DOMAIN_EXISTS:
		case ERROR_DOMAIN_LIMIT_EXCEEDED:
		case ERROR_INTERNAL_DB_CORRUPTION:
		case ERROR_INTERNAL_ERROR:
		case ERROR_GENERIC_NOT_MAPPED:
		case ERROR_BAD_DESCRIPTOR_FORMAT:
		case ERROR_NOT_LOGON_PROCESS:
		case ERROR_LOGON_SESSION_EXISTS:
		case ERROR_NO_SUCH_PACKAGE:
		case ERROR_BAD_LOGON_SESSION_STATE:
		case ERROR_LOGON_SESSION_COLLISION:
		case ERROR_INVALID_LOGON_TYPE:
		case ERROR_CANNOT_IMPERSONATE:
		case ERROR_RXACT_INVALID_STATE:
		case ERROR_RXACT_COMMIT_FAILURE:
		case ERROR_SPECIAL_ACCOUNT:
		case ERROR_SPECIAL_GROUP:
		case ERROR_SPECIAL_USER:
		case ERROR_MEMBERS_PRIMARY_GROUP:
		case ERROR_TOKEN_ALREADY_IN_USE:
		case ERROR_NO_SUCH_ALIAS:
		case ERROR_MEMBER_NOT_IN_ALIAS:
		case ERROR_MEMBER_IN_ALIAS:
		case ERROR_ALIAS_EXISTS:
		case ERROR_LOGON_NOT_GRANTED:
		case ERROR_TOO_MANY_SECRETS:
		case ERROR_SECRET_TOO_LONG:
		case ERROR_INTERNAL_DB_ERROR:
		case ERROR_TOO_MANY_CONTEXT_IDS:
		case ERROR_LOGON_TYPE_NOT_GRANTED:
		case ERROR_NT_CROSS_ENCRYPTION_REQUIRED:
		case ERROR_NO_SUCH_MEMBER:
		case ERROR_INVALID_MEMBER:
		case ERROR_TOO_MANY_SIDS:
		case ERROR_LM_CROSS_ENCRYPTION_REQUIRED:
		case ERROR_NO_INHERITANCE:
		case ERROR_FILE_CORRUPT:
		case ERROR_DISK_CORRUPT:
		case ERROR_NO_USER_SESSION_KEY:
		case ERROR_LICENSE_QUOTA_EXCEEDED:
		case ERROR_INVALID_WINDOW_HANDLE:
		case ERROR_INVALID_MENU_HANDLE:
		case ERROR_INVALID_CURSOR_HANDLE:
		case ERROR_INVALID_ACCEL_HANDLE:
		case ERROR_INVALID_HOOK_HANDLE:
		case ERROR_INVALID_DWP_HANDLE:
		case ERROR_TLW_WITH_WSCHILD:
		case ERROR_CANNOT_FIND_WND_CLASS:
		case ERROR_WINDOW_OF_OTHER_THREAD:
		case ERROR_HOTKEY_ALREADY_REGISTERED:
		case ERROR_CLASS_ALREADY_EXISTS:
		case ERROR_CLASS_DOES_NOT_EXIST:
		case ERROR_CLASS_HAS_WINDOWS:
		case ERROR_INVALID_INDEX:
		case ERROR_INVALID_ICON_HANDLE:
		case ERROR_PRIVATE_DIALOG_INDEX:
		case ERROR_LISTBOX_ID_NOT_FOUND:
		case ERROR_NO_WILDCARD_CHARACTERS:
		case ERROR_CLIPBOARD_NOT_OPEN:
		case ERROR_HOTKEY_NOT_REGISTERED:
		case ERROR_WINDOW_NOT_DIALOG:
		case ERROR_CONTROL_ID_NOT_FOUND:
		case ERROR_INVALID_COMBOBOX_MESSAGE:
		case ERROR_WINDOW_NOT_COMBOBOX:
		case ERROR_INVALID_EDIT_HEIGHT:
		case ERROR_DC_NOT_FOUND:
		case ERROR_INVALID_HOOK_FILTER:
		case ERROR_INVALID_FILTER_PROC:
		case ERROR_HOOK_NEEDS_HMOD:
		case ERROR_GLOBAL_ONLY_HOOK:
		case ERROR_JOURNAL_HOOK_SET:
		case ERROR_HOOK_NOT_INSTALLED:
		case ERROR_INVALID_LB_MESSAGE:
		case ERROR_SETCOUNT_ON_BAD_LB:
		case ERROR_LB_WITHOUT_TABSTOPS:
		case ERROR_DESTROY_OBJECT_OF_OTHER_THREAD:
		case ERROR_CHILD_WINDOW_MENU:
		case ERROR_NO_SYSTEM_MENU:
		case ERROR_INVALID_MSGBOX_STYLE:
		case ERROR_INVALID_SPI_VALUE:
		case ERROR_HWNDS_HAVE_DIFF_PARENT:
		case ERROR_NOT_CHILD_WINDOW:
		case ERROR_INVALID_GW_COMMAND:
		case ERROR_INVALID_THREAD_ID:
		case ERROR_NON_MDICHILD_WINDOW:
		case ERROR_POPUP_ALREADY_ACTIVE:
		case ERROR_NO_SCROLLBARS:
		case ERROR_INVALID_SCROLLBAR_RANGE:
		case ERROR_INVALID_SHOWWIN_COMMAND:
		case ERROR_NO_SYSTEM_RESOURCES:
		case ERROR_NONPAGED_SYSTEM_RESOURCES:
		case ERROR_PAGED_SYSTEM_RESOURCES:
		case ERROR_WORKING_SET_QUOTA:
		case ERROR_PAGEFILE_QUOTA:
		case ERROR_COMMITMENT_LIMIT:
		case ERROR_MENU_ITEM_NOT_FOUND:
		case ERROR_EVENTLOG_FILE_CORRUPT:
		case ERROR_EVENTLOG_CANT_START:
		case ERROR_LOG_FILE_FULL:
		case ERROR_EVENTLOG_FILE_CHANGED:
		case RPC_S_INVALID_STRING_BINDING:
		case RPC_S_WRONG_KIND_OF_BINDING:
		case RPC_S_INVALID_BINDING:
		case RPC_S_PROTSEQ_NOT_SUPPORTED:
		case RPC_S_INVALID_RPC_PROTSEQ:
		case RPC_S_INVALID_STRING_UUID:
		case RPC_S_INVALID_ENDPOINT_FORMAT:
		case RPC_S_INVALID_NET_ADDR:
		case RPC_S_NO_ENDPOINT_FOUND:
		case RPC_S_INVALID_TIMEOUT:
		case RPC_S_OBJECT_NOT_FOUND:
		case RPC_S_ALREADY_REGISTERED:
		case RPC_S_TYPE_ALREADY_REGISTERED:
		case RPC_S_ALREADY_LISTENING:
		case RPC_S_NO_PROTSEQS_REGISTERED:
		case RPC_S_NOT_LISTENING:
		case RPC_S_UNKNOWN_MGR_TYPE:
		case RPC_S_UNKNOWN_IF:
		case RPC_S_NO_BINDINGS:
		case RPC_S_NO_PROTSEQS:
		case RPC_S_CANT_CREATE_ENDPOINT:
		case RPC_S_OUT_OF_RESOURCES:
		case RPC_S_SERVER_UNAVAILABLE:
		case RPC_S_SERVER_TOO_BUSY:
		case RPC_S_INVALID_NETWORK_OPTIONS:
		case RPC_S_NO_CALL_ACTIVE:
		case RPC_S_CALL_FAILED:
		case RPC_S_CALL_FAILED_DNE:
		case RPC_S_PROTOCOL_ERROR:
		case RPC_S_UNSUPPORTED_TRANS_SYN:
		case RPC_S_UNSUPPORTED_TYPE:
		case RPC_S_INVALID_TAG:
		case RPC_S_INVALID_BOUND:
		case RPC_S_NO_ENTRY_NAME:
		case RPC_S_INVALID_NAME_SYNTAX:
		case RPC_S_UNSUPPORTED_NAME_SYNTAX:
		case RPC_S_UUID_NO_ADDRESS:
		case RPC_S_DUPLICATE_ENDPOINT:
		case RPC_S_UNKNOWN_AUTHN_TYPE:
		case RPC_S_MAX_CALLS_TOO_SMALL:
		case RPC_S_STRING_TOO_LONG:
		case RPC_S_PROTSEQ_NOT_FOUND:
		case RPC_S_PROCNUM_OUT_OF_RANGE:
		case RPC_S_BINDING_HAS_NO_AUTH:
		case RPC_S_UNKNOWN_AUTHN_SERVICE:
		case RPC_S_UNKNOWN_AUTHN_LEVEL:
		case RPC_S_INVALID_AUTH_IDENTITY:
		case RPC_S_UNKNOWN_AUTHZ_SERVICE:
		case EPT_S_INVALID_ENTRY:
		case EPT_S_CANT_PERFORM_OP:
		case EPT_S_NOT_REGISTERED:
		case RPC_S_NOTHING_TO_EXPORT:
		case RPC_S_INCOMPLETE_NAME:
		case RPC_S_INVALID_VERS_OPTION:
		case RPC_S_NO_MORE_MEMBERS:
		case RPC_S_NOT_ALL_OBJS_UNEXPORTED:
		case RPC_S_INTERFACE_NOT_FOUND:
		case RPC_S_ENTRY_ALREADY_EXISTS:
		case RPC_S_ENTRY_NOT_FOUND:
		case RPC_S_NAME_SERVICE_UNAVAILABLE:
		case RPC_S_INVALID_NAF_ID:
		case RPC_S_CANNOT_SUPPORT:
		case RPC_S_NO_CONTEXT_AVAILABLE:
		case RPC_S_INTERNAL_ERROR:
		case RPC_S_ZERO_DIVIDE:
		case RPC_S_ADDRESS_ERROR:
		case RPC_S_FP_DIV_ZERO:
		case RPC_S_FP_UNDERFLOW:
		case RPC_S_FP_OVERFLOW:
		case RPC_X_NO_MORE_ENTRIES:
		case RPC_X_SS_CHAR_TRANS_OPEN_FAIL:
		case RPC_X_SS_CHAR_TRANS_SHORT_FILE:
		case RPC_X_SS_IN_NULL_CONTEXT:
		case RPC_X_SS_CONTEXT_DAMAGED:
		case RPC_X_SS_HANDLES_MISMATCH:
		case RPC_X_SS_CANNOT_GET_CALL_HANDLE:
		case RPC_X_NULL_REF_POINTER:
		case RPC_X_ENUM_VALUE_OUT_OF_RANGE:
		case RPC_X_BYTE_COUNT_TOO_SMALL:
		case RPC_X_BAD_STUB_DATA:
		case ERROR_INVALID_USER_BUFFER:
		case ERROR_UNRECOGNIZED_MEDIA:
		case ERROR_NO_TRUST_LSA_SECRET:
		case ERROR_NO_TRUST_SAM_ACCOUNT:
		case ERROR_TRUSTED_DOMAIN_FAILURE:
		case ERROR_TRUSTED_RELATIONSHIP_FAILURE:
		case ERROR_TRUST_FAILURE:
		case RPC_S_CALL_IN_PROGRESS:
		case ERROR_NETLOGON_NOT_STARTED:
		case ERROR_ACCOUNT_EXPIRED:
		case ERROR_REDIRECTOR_HAS_OPEN_HANDLES:
		case ERROR_PRINTER_DRIVER_ALREADY_INSTALLED:
		case ERROR_UNKNOWN_PORT:
		case ERROR_UNKNOWN_PRINTER_DRIVER:
		case ERROR_UNKNOWN_PRINTPROCESSOR:
		case ERROR_INVALID_SEPARATOR_FILE:
		case ERROR_INVALID_PRIORITY:
		case ERROR_INVALID_PRINTER_NAME:
		case ERROR_PRINTER_ALREADY_EXISTS:
		case ERROR_INVALID_PRINTER_COMMAND:
		case ERROR_INVALID_DATATYPE:
		case ERROR_INVALID_ENVIRONMENT:
		case RPC_S_NO_MORE_BINDINGS:
		case ERROR_NOLOGON_INTERDOMAIN_TRUST_ACCOUNT:
		case ERROR_NOLOGON_WORKSTATION_TRUST_ACCOUNT:
		case ERROR_NOLOGON_SERVER_TRUST_ACCOUNT:
		case ERROR_DOMAIN_TRUST_INCONSISTENT:
		case ERROR_SERVER_HAS_OPEN_HANDLES:
		case ERROR_RESOURCE_DATA_NOT_FOUND:
		case ERROR_RESOURCE_TYPE_NOT_FOUND:
		case ERROR_RESOURCE_NAME_NOT_FOUND:
		case ERROR_RESOURCE_LANG_NOT_FOUND:
		case RPC_S_NO_INTERFACES:
		case RPC_S_CALL_CANCELLED:
		case RPC_S_BINDING_INCOMPLETE:
		case RPC_S_COMM_FAILURE:
		case RPC_S_UNSUPPORTED_AUTHN_LEVEL:
		case RPC_S_NO_PRINC_NAME:
		case RPC_S_NOT_RPC_ERROR:
		case RPC_S_UUID_LOCAL_ONLY:
		case RPC_S_SEC_PKG_ERROR:
		case RPC_S_NOT_CANCELLED:
		case RPC_X_INVALID_ES_ACTION:
		case RPC_X_WRONG_ES_VERSION:
		case RPC_X_WRONG_STUB_VERSION:
		case RPC_S_GROUP_MEMBER_NOT_FOUND:
		case EPT_S_CANT_CREATE:
		case RPC_S_INVALID_OBJECT:
		case ERROR_INVALID_TIME:
		case ERROR_INVALID_FORM_NAME:
		case ERROR_INVALID_FORM_SIZE:
		case ERROR_ALREADY_WAITING:
		case ERROR_PRINTER_DELETED:
		case ERROR_INVALID_PRINTER_STATE:
		case ERROR_PASSWORD_MUST_CHANGE:
		case ERROR_DOMAIN_CONTROLLER_NOT_FOUND:
		case ERROR_ACCOUNT_LOCKED_OUT:
		case ERROR_NO_BROWSER_SERVERS_FOUND:
		case ERROR_INVALID_PIXEL_FORMAT:
		case ERROR_BAD_DRIVER:
		case ERROR_INVALID_WINDOW_STYLE:
		case ERROR_METAFILE_NOT_SUPPORTED:
		case ERROR_TRANSFORM_NOT_SUPPORTED:
		case ERROR_CLIPPING_NOT_SUPPORTED:
		case ERROR_UNKNOWN_PRINT_MONITOR:
		case ERROR_PRINTER_DRIVER_IN_USE:
		case ERROR_SPOOL_FILE_NOT_FOUND:
		case ERROR_SPL_NO_STARTDOC:
		case ERROR_SPL_NO_ADDJOB:
		case ERROR_PRINT_PROCESSOR_ALREADY_INSTALLED:
		case ERROR_PRINT_MONITOR_ALREADY_INSTALLED:
		case ERROR_WINS_INTERNAL:
		case ERROR_CAN_NOT_DEL_LOCAL_WINS:
		case ERROR_STATIC_INIT:
		case ERROR_INC_BACKUP:
		case ERROR_FULL_BACKUP:
		case ERROR_REC_NON_EXISTENT:
		case ERROR_RPL_NOT_ALLOWED:
		case SEVERITY_SUCCESS:
		case SEVERITY_ERROR:
		case ILITY_WINDOWS:
		case ILITY_STORAGE:
		case ILITY_RPC:
		case ILITY_WIN32:
		case ILITY_CONTROL:
		case ILITY_NULL:
		case ILITY_ITF:
		case ILITY_DISPATCH:
		case SUCCEEDED(Status):((HRESULT)(Status):>=:)
		case ILED(Status):((HRESULT)(Status)<0)
		case IS_ERROR(Status):((unsigned:long)(Status):>>::==:SEVERITY_ERROR)
		case HRESULT_CODE(r):((r)&0x)
		case SCODE_CODE(c):((c)&0x)
		case HRESULT_FACILITY(r):(((r)>>16)&0xfff)
		case SCODE_FACILITY(c):(((c)>>16)&0xfff)
		case HRESULT_SEVERITY(r):(((r)>>31)&0x)
		case SCODE_SEVERITY(c):(((c)>>31)&0x)
		case MAKE_HRESULT(s,f,c):((HRESULT)(((unsigned:long)(s)<<31)|((unsigned:long)(f)<<16)|((unsigned:long)(c))))
		case MAKE_SCODE(s,f,c):((SCODE)(((unsigned:long)(s)<<31)|((unsigned:long)(f)<<16)|((unsigned:long)(c))):)
		case ILITY_NT_BIT:0x
		case HRESULT_FROM_WIN32(x):(x?((HRESULT)(((x)&0x)|(FACILITY_WIN32<<16)|0x)):0)
		case HRESULT_FROM_NT(x):((HRESULT)((x)|FACILITY_NT_BIT))
		case GetScode(hr):((SCODE):(hr))
		case ResultFromScode(sc):((HRESULT):(sc))
		case PropagateResult(hrPrevious,:scBase):((HRESULT):scBase)
		case NOERROR:S_OK
		case E_UNEXPECTED:
		case E_NOTIMPL:
		case E_OUTOFMEMORY:
		case E_INVALIDARG:
		case E_NOINTERFACE:
		case E_POINTER:
		case E_HANDLE:
		case E_ABORT:
		case E_FAIL:
		case E_ACCESSDENIED:
		case O_E_INIT_TLS:
		case O_E_INIT_SHARED_ALLOCATOR:
		case O_E_INIT_MEMORY_ALLOCATOR:
		case O_E_INIT_CLASS_CACHE:
		case O_E_INIT_RPC_CHANNEL:
		case O_E_INIT_TLS_SET_CHANNEL_CONTROL:
		case O_E_INIT_TLS_CHANNEL_CONTROL:
		case O_E_INIT_UNACCEPTED_USER_ALLOCATOR:
		case O_E_INIT_SCM_MUTEX_EXISTS:
		case O_E_INIT_SCM_FILE_MAPPING_EXISTS:
		case O_E_INIT_SCM_MAP_VIEW_OF_FILE:
		case O_E_INIT_SCM_EXEC_FAILURE:
		case O_E_INIT_ONLY_SINGLE_THREADED:
		case S_OK:()
		case S_FALSE:()
		case OLE_E_FIRST:
		case OLE_E_LAST:
		case OLE_S_FIRST:
		case OLE_S_LAST:
		case OLE_E_OLEVERB:
		case OLE_E_ADVF:
		case OLE_E_ENUM_NOMORE:
		case OLE_E_ADVISENOTSUPPORTED:
		case OLE_E_NOCONNECTION:
		case OLE_E_NOTRUNNING:
		case OLE_E_NOCACHE:
		case OLE_E_BLANK:
		case OLE_E_CLASSDIFF:
		case OLE_E_CANT_GETMONIKER:
		case OLE_E_CANT_BINDTOSOURCE:
		case OLE_E_STATIC:
		case OLE_E_PROMPTSAVECANCELLED:
		case OLE_E_INVALIDRECT:
		case OLE_E_WRONGCOMPOBJ:
		case OLE_E_INVALIDHWND:
		case OLE_E_NOT_INPLACEACTIVE:
		case OLE_E_CANTCONVERT:
		case OLE_E_NOSTORAGE:
		case V_E_FORMATETC:
		case V_E_DVTARGETDEVICE:
		case V_E_STGMEDIUM:
		case V_E_STATDATA:
		case V_E_LINDEX:
		case V_E_TYMED:
		case V_E_CLIPFORMAT:
		case V_E_DVASPECT:
		case V_E_DVTARGETDEVICE_SIZE:
		case V_E_NOIVIEWOBJECT:
		case RAGDROP_E_FIRST:
		case RAGDROP_E_LAST:
		case RAGDROP_S_FIRST:
		case RAGDROP_S_LAST:
		case RAGDROP_E_NOTREGISTERED:
		case RAGDROP_E_ALREADYREGISTERED:
		case RAGDROP_E_INVALIDHWND:
		case SSFACTORY_E_FIRST:
		case SSFACTORY_E_LAST:
		case SSFACTORY_S_FIRST:
		case SSFACTORY_S_LAST:
		case SS_E_NOAGGREGATION:
		case SS_E_CLASSNOTAVAILABLE:
		case MARSHAL_E_FIRST:
		case MARSHAL_E_LAST:
		case MARSHAL_S_FIRST:
		case MARSHAL_S_LAST:
		case TA_E_FIRST:
		case TA_E_LAST:
		case TA_S_FIRST:
		case TA_S_LAST:
		case VIEW_E_FIRST:
		case VIEW_E_LAST:
		case VIEW_S_FIRST:
		case VIEW_S_LAST:
		case VIEW_E_DRAW:
		case REGDB_E_FIRST:
		case REGDB_E_LAST:
		case REGDB_S_FIRST:
		case REGDB_S_LAST:
		case REGDB_E_READREGDB:
		case REGDB_E_WRITEREGDB:
		case REGDB_E_KEYMISSING:
		case REGDB_E_INVALIDVALUE:
		case REGDB_E_CLASSNOTREG:
		case REGDB_E_IIDNOTREG:
		case HE_E_FIRST:
		case HE_E_LAST:
		case HE_S_FIRST:
		case HE_S_LAST:
		case HE_E_NOCACHE_UPDATED:
		case OLEOBJ_E_FIRST:
		case OLEOBJ_E_LAST:
		case OLEOBJ_S_FIRST:
		case OLEOBJ_S_LAST:
		case OLEOBJ_E_NOVERBS:
		case OLEOBJ_E_INVALIDVERB:
		case IENTSITE_E_FIRST:
		case IENTSITE_E_LAST:
		case IENTSITE_S_FIRST:
		case IENTSITE_S_LAST:
		case INPLACE_E_NOTUNDOABLE:
		case INPLACE_E_NOTOOLSPACE:
		case INPLACE_E_FIRST:
		case INPLACE_E_LAST:
		case INPLACE_S_FIRST:
		case INPLACE_S_LAST:
		case ENUM_E_FIRST:
		case ENUM_E_LAST:
		case ENUM_S_FIRST:
		case ENUM_S_LAST:
		case ONVERT10_E_FIRST:
		case ONVERT10_E_LAST:
		case ONVERT10_S_FIRST:
		case ONVERT10_S_LAST:
		case ONVERT10_E_OLESTREAM_GET:
		case ONVERT10_E_OLESTREAM_PUT:
		case ONVERT10_E_OLESTREAM_FMT:
		case ONVERT10_E_OLESTREAM_BITMAP_TO_DIB:
		case ONVERT10_E_STG_FMT:
		case ONVERT10_E_STG_NO_STD_STREAM:
		case ONVERT10_E_STG_DIB_TO_BITMAP:
		case IPBRD_E_FIRST:
		case IPBRD_E_LAST:
		case IPBRD_S_FIRST:
		case IPBRD_S_LAST:
		case IPBRD_E_CANT_OPEN:
		case IPBRD_E_CANT_EMPTY:
		case IPBRD_E_CANT_SET:
		case IPBRD_E_BAD_DATA:
		case IPBRD_E_CANT_CLOSE:
		case MK_E_FIRST:
		case MK_E_LAST:
		case MK_S_FIRST:
		case MK_S_LAST:
		case MK_E_CONNECTMANUALLY:
		case MK_E_EXCEEDEDDEADLINE:
		case MK_E_NEEDGENERIC:
		case MK_E_UNAVAILABLE:
		case MK_E_SYNTAX:
		case MK_E_NOOBJECT:
		case MK_E_INVALIDEXTENSION:
		case MK_E_INTERMEDIATEINTERFACENOTSUPPORTED:
		case MK_E_NOTBINDABLE:
		case MK_E_NOTBOUND:
		case MK_E_CANTOPENFILE:
		case MK_E_MUSTBOTHERUSER:
		case MK_E_NOINVERSE:
		case MK_E_NOSTORAGE:
		case MK_E_NOPREFIX:
		case MK_E_ENUMERATION_FAILED:
		case O_E_FIRST:
		case O_E_LAST:
		case O_S_FIRST:
		case O_S_LAST:
		case O_E_NOTINITIALIZED:
		case O_E_ALREADYINITIALIZED:
		case O_E_CANTDETERMINECLASS:
		case O_E_CLASSSTRING:
		case O_E_IIDSTRING:
		case O_E_APPNOTFOUND:
		case O_E_APPSINGLEUSE:
		case O_E_ERRORINAPP:
		case O_E_DLLNOTFOUND:
		case O_E_ERRORINDLL:
		case O_E_WRONGOSFORAPP:
		case O_E_OBJNOTREG:
		case O_E_OBJISREG:
		case O_E_OBJNOTCONNECTED:
		case O_E_APPDIDNTREG:
		case O_E_RELEASED:
		case OLE_S_USEREG:
		case OLE_S_STATIC:
		case OLE_S_MAC_CLIPFORMAT:
		case RAGDROP_S_DROP:
		case RAGDROP_S_CANCEL:
		case RAGDROP_S_USEDEFAULTCURSORS:
		case TA_S_SAMEFORMATETC:
		case VIEW_S_ALREADY_FROZEN:
		case HE_S_FORMATETC_NOTSUPPORTED:
		case HE_S_SAMECACHE:
		case HE_S_SOMECACHES_NOTUPDATED:
		case OLEOBJ_S_INVALIDVERB:
		case OLEOBJ_S_CANNOT_DOVERB_NOW:
		case OLEOBJ_S_INVALIDHWND:
		case INPLACE_S_TRUNCATED:
		case ONVERT10_S_NO_PRESENTATION:
		case MK_S_REDUCED_TO_SELF:
		case MK_S_ME:
		case MK_S_HIM:
		case MK_S_US:
		case MK_S_MONIKERALREADYREGISTERED:
		case O_E_CLASS_CREATE_FAILED:
		case O_E_SCM_ERROR:
		case O_E_SCM_RPC_FAILURE:
		case O_E_BAD_PATH:
		case O_E_SERVER_EXEC_FAILURE:
		case O_E_OBJSRV_RPC_FAILURE:
		case MK_E_NO_NORMALIZED:
		case O_E_SERVER_STOPPING:
		case MEM_E_INVALID_ROOT:
		case MEM_E_INVALID_LINK:
		case MEM_E_INVALID_SIZE:
		case ISP_E_UNKNOWNINTERFACE:
		case ISP_E_MEMBERNOTFOUND:
		case ISP_E_PARAMNOTFOUND:
		case ISP_E_TYPEMISMATCH:
		case ISP_E_UNKNOWNNAME:
		case ISP_E_NONAMEDARGS:
		case ISP_E_BADVARTYPE:
		case ISP_E_EXCEPTION:
		case ISP_E_OVERFLOW:
		case ISP_E_BADINDEX:
		case ISP_E_UNKNOWNLCID:
		case ISP_E_ARRAYISLOCKED:
		case ISP_E_BADPARAMCOUNT:
		case ISP_E_PARAMNOTOPTIONAL:
		case ISP_E_BADCALLEE:
		case ISP_E_NOTACOLLECTION:
		case TYPE_E_BUFFERTOOSMALL:
		case TYPE_E_INVDATAREAD:
		case TYPE_E_UNSUPFORMAT:
		case TYPE_E_REGISTRYACCESS:
		case TYPE_E_LIBNOTREGISTERED:
		case TYPE_E_UNDEFINEDTYPE:
		case TYPE_E_QUALIFIEDNAMEDISALLOWED:
		case TYPE_E_INVALIDSTATE:
		case TYPE_E_WRONGTYPEKIND:
		case TYPE_E_ELEMENTNOTFOUND:
		case TYPE_E_AMBIGUOUSNAME:
		case TYPE_E_NAMECONFLICT:
		case TYPE_E_UNKNOWNLCID:
		case TYPE_E_DLLFUNCTIONNOTFOUND:
		case TYPE_E_BADMODULEKIND:
		case TYPE_E_DUPLICATEID:
		case TYPE_E_INVALIDID:
		case TYPE_E_TYPEMISMATCH:
		case TYPE_E_OUTOFBOUNDS:
		case TYPE_E_IOERROR:
		case TYPE_E_CANTCREATETMPFILE:
		case TYPE_E_CANTLOADLIBRARY:
		case TYPE_E_INCONSISTENTPROPFUNCS:
		case TYPE_E_CIRCULARTYPE:
		case STG_E_INVALIDFUNCTION:
		case STG_E_FILENOTFOUND:
		case STG_E_PATHNOTFOUND:
		case STG_E_TOOMANYOPENFILES:
		case STG_E_ACCESSDENIED:
		case STG_E_INVALIDHANDLE:
		case STG_E_INSUFFICIENTMEMORY:
		case STG_E_INVALIDPOINTER:
		case STG_E_NOMOREFILES:
		case STG_E_DISKISWRITEPROTECTED:
		case STG_E_SEEKERROR:
		case STG_E_WRITEFAULT:
		case STG_E_READFAULT:
		case STG_E_SHAREVIOLATION:
		case STG_E_FILEALREADYEXISTS:
		case STG_E_INVALIDPARAMETER:
		case STG_E_MEDIUMFULL:
		case STG_E_ABNORMALAPIEXIT:
		case STG_E_INVALIDHEADER:
		case STG_E_INVALIDNAME:
		case STG_E_UNKNOWN:
		case STG_E_UNIMPLEMENTEDFUNCTION:
		case STG_E_INVALIDFLAG:
		case STG_E_NOTCURRENT:
		case STG_E_REVERTED:
		case STG_E_CANTSAVE:
		case STG_E_OLDFORMAT:
		case STG_E_OLDDLL:
		case STG_E_SHAREREQUIRED:
		case STG_E_NOTFILEBASEDSTORAGE:
		case STG_E_EXTANTMARSHALLINGS:
		case STG_S_CONVERTED:
		case RPC_E_CALL_REJECTED:
		case RPC_E_CALL_CANCELED:
		case RPC_E_CANTPOST_INSENDCALL:
		case RPC_E_CANTCALLOUT_INASYNCCALL:
		case RPC_E_CANTCALLOUT_INEXTERNALCALL:
		case RPC_E_CONNECTION_TERMINATED:
		case RPC_E_SERVER_DIED:
		case RPC_E_CLIENT_DIED:
		case RPC_E_INVALID_DATAPACKET:
		case RPC_E_CANTTRANSMIT_CALL:
		case RPC_E_CLIENT_CANTMARSHAL_DATA:
		case RPC_E_CLIENT_CANTUNMARSHAL_DATA:
		case RPC_E_SERVER_CANTMARSHAL_DATA:
		case RPC_E_SERVER_CANTUNMARSHAL_DATA:
		case RPC_E_INVALID_DATA:
		case RPC_E_INVALID_PARAMETER:
		case RPC_E_CANTCALLOUT_AGAIN:
		case RPC_E_SERVER_DIED_DNE:
		case RPC_E_SYS_CALL_FAILED:
		case RPC_E_OUT_OF_RESOURCES:
		case RPC_E_ATTEMPTED_MULTITHREAD:
		case RPC_E_NOT_REGISTERED:
		case RPC_E_FAULT:
		case RPC_E_SERVERFAULT:
		case RPC_E_CHANGED_MODE:
		case RPC_E_INVALIDMETHOD:
		case RPC_E_DISCONNECTED:
		case RPC_E_RETRY:
		case RPC_E_SERVERCALL_RETRYLATER:
		case RPC_E_SERVERCALL_REJECTED:
		case RPC_E_INVALID_CALLDATA:
		case RPC_E_CANTCALLOUT_ININPUTSYNCCALL:
		case RPC_E_WRONG_THREAD:
		case RPC_E_THREAD_NOT_INIT:
		case RPC_E_UNEXPECTED:


		case ERROR_IS_JOIN_TARGET:
		case ERROR_IS_JOINED:
		case ERROR_IS_SUBSTED:
		case ERROR_NOT_JOINED:
		case ERROR_NOT_SUBSTED:
		case ERROR_JOIN_TO_JOIN:
		case ERROR_SUBST_TO_SUBST:
		case ERROR_JOIN_TO_SUBST:
		case ERROR_SUBST_TO_JOIN:
		case ERROR_SAME_DRIVE:
		case ERROR_DIR_NOT_ROOT:
		case ERROR_DIR_NOT_EMPTY:
		case ERROR_IS_SUBST_PATH:
		case ERROR_IS_JOIN_PATH:
		case ERROR_IS_SUBST_TARGET:
#endif




		default:
//fprintf(stderr,"WINDOWS UNKNOWNERR=%d $%x\n",err,err);

			result=ICVM_EUNKNOWN;break;
	}
	return result;
}
#endif // __WIN32__






