
all:
#	cd FS;make
	cd ICE;make
#	cd PEX5;make
	cd SM;make
	cd X11;make
	cd Xau;make
	cd Xaw;make
	cd Xdmcp;make
	cd Xext;make
	cd Xi;make
	cd Xmu;make
	cd Xp;make
	cd Xt;make
	cd Xtst;make
	cd xkbfile;make
	cd XIE;make

clean:
#	cd FS;make -i clean
	cd ICE;make -i clean
#	cd PEX5;make -i clean
	cd SM;make -i clean
	cd X11;make -i clean
	cd Xau;make -i clean
	cd Xaw;make -i clean
	cd Xdmcp;make -i clean
	cd Xext;make -i clean
	cd Xi;make -i clean
	cd Xmu;make -i clean
	cd Xp;make -i clean
	cd Xt;make -i clean
	cd Xtst;make -i clean
	cd xkbfile;make -i clean
	cd XIE;make -i clean


install: all
#	cd FS;make install
	cd ICE;make install
#	cd PEX5;make install
	cd SM;make install
	cd X11;make install
	cd Xau;make install
	cd Xaw;make install
	cd Xdmcp;make install
	cd Xext;make install
	cd Xi;make install
	cd Xmu;make install
	cd Xp;make install
	cd Xt;make install
	cd Xtst;make install
	cd xkbfile;make install
	cd XIE;make install


