
AR=iar -qc 
RANLIB=iranlib 
LD=ild


all:
	cd btree;make
	cd hash;make
	cd db;make
	cd mpool;make
	cd recno;make
clean:
	cd btree;make -i clean
	cd hash;make -i clean
	cd db;make -i clean
	cd mpool;make -i clean
	cd recno;make -i clean



